export enum Routes {
  LOGIN = 'LOGIN_SCREEN',
  SUBCONTRACTOR_LOGIN = 'SUBCONTRACTOR_LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_EMAIL_SENT = 'FORGOT_PASSWORD_EMAIL_SENT',
  HELP_SUPPORT = 'HELP_SUPPORT',
  LEARN_HOW_TO_OPEN = 'LEARN_HOW_TO_OPEN',
}
