export enum Routes {
  CREATE_FLASHING = 'CREATE_FLASHING',
  ALL_JOBS='ALL_JOBS',
  GUTTER_FLASHING = 'GUTTER_FLASHING',
  DEMO = 'Demo_FLASHING',
  DEMO_BOARD = 'DEMO_BOARD',
  JOB_DETAILS = 'JOB_DETAILS',
  CREATE_JOB = 'CREATE_JOB',
  GUTTER_FLASHING_EXAMPLES = 'GUTTER_FLASHING_EXAMPLES'
}
