export enum Routes {
  CREATE_FLASHING = 'CREATE_FLASHING',
  GUTTER_FLASHING = 'GUTTER_FLASHING',
  DEMO = 'Demo_FLASHING',
  GUTTER_FLASHING_EXAMPLES = 'GUTTER_FLASHING_EXAMPLES',
  CREATE_RAINHEAD = 'CREATE_RAINHEAD',
}
