export enum Routes {
  LOGIN = 'LOGIN_SCREEN',
  CREATE_FLASHING = 'CREATE_FLASHING',
  ALL_JOBS='ALL_JOBS',
  GUTTER_FLASHING = 'GUTTER_FLASHING',
  DEMO = 'Demo_FLASHING',
  DEMO_BOARD = 'DEMO_BOARD',
  JOB_DETAILS = 'JOB_DETAILS',
  CREATE_JOB = 'CREATE_JOB',
  GUTTER_FLASHING_EXAMPLES = 'GUTTER_FLASHING_EXAMPLES',
  SUBCONTRACTOR_LOGIN = 'SUBCONTRACTOR_LOGIN',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
  FORGOT_PASSWORD_EMAIL_SENT = 'FORGOT_PASSWORD_EMAIL_SENT',
  HELP_SUPPORT = 'HELP_SUPPORT',
  LEARN_HOW_TO_OPEN = 'LEARN_HOW_TO_OPEN',
  CREATE_RAINHEAD = 'CREATE_RAINHEAD'
}
