export const config = {
  baseUrl: 'https://api.trak.co',
  baseUrlPdf: 'https://files-staging.paperplane.app/',
  emailsToShared: [
    'burdens.orders@tradetrak.com.au',
    'matt.celima@burdens.com.au',
    'owenm@trak.co',
    'markm@trak.co',
    'mat@digitalbasis.com.au',
    'jeff@digitalbasis.com',
    'steveb@trak.co',
  ],
  messageToShared: 'Thanks for your Flashings order',
  urlStoreIOS:
    'https://apps.apple.com/co/app/burdens-flashing-designer/id6449658670',
  urlStoreAndroid:
    'https://play.google.com/store/apps/details?id=com.flashings',
  credentialsMO: '53eAdpfCR3ZPfHJthoUxWNA7:',
  // template for generate pdf file
  templateIdDefault: 'BLAN309970',
  templateId4_6: 'BLAN321701',
  templateId7_9: 'BLAN935154',
  templateId10_12: 'BLAN823895',
  templateId13_15: 'BLAN384760',
  intervalForGettingVersionApp: 7200,
  nameJobMaximum: 40,
  unitMeasurement: 'mm',
  unitMeasurementPdf: 'mm',
  maxFolds: 7,
  maxGirth: 1200,
  maxGirthPhone: 1200,
  maxGirthTable: 2163,
  SKU_TAPERED: 'MFLTAPER',
  SKU_DEFAULT: 'MFLC10100218',
  minimumSizeLinesMM: 10,
};
